name: Go Test

on: [push, pull_request]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: "1.21"

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: go test -p 1 ./...
